apps:
  name: 'loki'
  version: '1.0.0'
server:
  port: 9090
database:
  url: 'loki'
  port: '5432'
  databaseName: 'loki'
  username: 'loki'
  password: 'loki'
  schema: 'loki'
  connectionTimeout: '20s'
  maxIdleConnection: 5
  maxOpenConnection: 10
  debugMode: true